---
name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 🚀 Features
    label: feature

  - title: 🐛 Bug Fixes
    label: bug

  - title: 🧰 Maintenance
    label: chore

  - title: 📖 Documentation
    label: documentation

version-resolver:
  major:
    labels: [major]

  minor:
    labels: [minor]

  patch:
    labels: [patch]

  default: patch
