---
repository:
  name: ansible
  description: My personal ansible setup for my workstations and servers.
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false
  has_pages: false
  has_downloads: false

  is_template: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true

  allow_forking: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: CC0000
    description: An issue with the system 🐛.

  - name: feature
    color: 336699
    description: New functionality.

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
