---
name: Main
'on':
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macos-11
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install test dependencies
        run: pip3 install ansible-core ansible-lint yamllint molecule molecule-vagrant

      - name: Test
        run: molecule test
