---
name: Main
'on':
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    steps:
      - name: Release
        uses: release-drafter/release-drafter@v5.19.0
        publish: true
