---
name: Pull Request
'on':
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  check-branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: ^([a-z]+)\/([a-z]+)$
          allowed_prefixes: break,feat,bug,chore,docs

  label:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}