---
name: Test
'on':
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: pip

      - name: Install test dependencies
        run: pip install -r requirements.txt

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('molecule/default/molecule.yml') }}
          restore-keys: ${{ runner.os }}-vagrant-

      - name: Test
        run: molecule test
        env:
          PY_COLORS: 1
